services:
  php:
    build:
      context: ./docker/php
    volumes:
      - .:/var/www/html
    ports:
      - "${AppPort}:80"
    depends_on:
      - mysql
    environment:
      DB_HOST: ${DatabaseHost}
      DB_NAME: ${DatabaseName}
      DB_USER: ${DatabaseUser}
      DB_PASSWORD: ${DatabasePassword}

  mysql:
    image: mysql:8.0
    ports:
      - "${DatabasePort}:3306"
    environment:
      MYSQL_DATABASE: ${DatabaseName}
      MYSQL_USER: ${DatabaseUser}
      MYSQL_PASSWORD: ${DatabasePassword}
      MYSQL_ROOT_PASSWORD: ${DatabaseRootPassword}
    volumes:
      - mysql_data:/var/lib/mysql
      - ./docker/mysql/init.sql:/docker-entrypoint-initdb.d/init.sql

volumes:
  mysql_data:
